### ISSUE TITLE
Any HuggingFace space for a use?

### ISSUE THREAD

**Issue by zhimin-z** [InstantID/InstantID#10]
That model is really a great stuff, and I hope to play with it asap :)

**Comment by haofanwang** [comment]
Yes, it will be on hf space in the next few days.

**Comment by SlZeroth** [comment]
@haofanwang code will release in the next few days too?

**Comment by haofanwang** [comment]
Yes.

**Comment by platform-kit** [comment]
@haofanwang did you take steps to make the training data inclusive of all races?

**Comment by haofanwang** [comment]
We use LAION-Face as one of our training datasets to ensure the diversity.

**Comment by wangqixun** [comment]
> We use LAION-Face as one of our training datasets to ensure the diversity.

@platform-kit  To be precise, the data is not the entire LAION-Face. Approximately 23 million images were used.

**Comment by h3clikejava** [comment]
![image](https://github.com/InstantID/InstantID/assets/4688773/b69a1ac6-f097-4bd3-9be6-7f3b2496c234)

Why the result same with input?

**Comment by ResearcherXman** [comment]
Ah, it is a template. It's ready now! @h3clikejava

**Comment by wangqixun** [comment]
https://huggingface.co/spaces/InstantX/InstantID




![企业微信截图_73b31371-6b76-4392-9c0d-90a9d99c1dee](https://github.com/InstantID/InstantID/assets/46553287/98fa8dd6-6c16-436a-bf67-f08a9aa3871e)
