### ISSUE TITLE
difference between this repo and the online demo

### ISSUE THREAD

**Issue by maksimstw** [InstantID/InstantID#106]
Could you please elaborate a bit on the differences between this repo and the online demo?

The official online demo seems to have better generation quality. The images I generated using this repo are also different from the ones generated by the online demo despite using the same seed, CFG, etc. This repo also does not have the "enhance non-face region" option. What could be the issue?

**Comment by ResearcherXman** [comment]
We will update soon to make them consistent.

**Comment by shoutOutYangJie** [comment]
> We will update soon to make them consistent.

so many people are using your online demo and I must wait more than 20 mins. If you can make the local demo and online demo consistent, it will be nice since we can use our machine
