### ISSUE TITLE
inswapper_128 beat you in any case

### ISSUE THREAD

**Issue by vduck** [InstantID/InstantID#11]
inswapper_128 beat you in any case

**Comment by haofanwang** [comment]
❤️

**Comment by wangqixun** [comment]
> ❤️

挨打要立正！！吾日三省吾身，Hinton点赞了吗？Bengio点赞了吗？LeCun点赞了吗？

**Comment by wangqixun** [comment]
> > ❤️
> 
> 挨打要立正！！吾日三省吾身，Hinton点赞了吗？Bengio点赞了吗？LeCun点赞了吗？

lecun点了！
