### ISSUE TITLE
What about the implementation of sdxl inpaint pipeline?

### ISSUE THREAD

**Issue by zengjie617789** [InstantID/InstantID#112]
Based on the great work, I modified some code to implement inpaint pipeline. I found it lose the ID face feature totally, and sometime failed to align mask region with the referenced face.  Here are results below:
original image:
![wuyanzu (3)](https://github.com/InstantID/InstantID/assets/25050291/8bca66a9-c2f4-4b25-90cf-49e75dfbf95b)
mask image:
![wuyanzu-mask](https://github.com/InstantID/InstantID/assets/25050291/20f0aa1e-e16a-4fed-8011-021123968279)
results:

![temp](https://github.com/InstantID/InstantID/assets/25050291/54eb8d42-3d02-48d5-b3b4-5c6d50ee3d28)
![2024-01-31_17-01-57_633f9b24c01711eeb0c63cecefba3494_0_0 8_0 8_5](https://github.com/InstantID/InstantID/assets/25050291/733af883-aa4d-4f24-a9da-2b9152384751)
Any suggetions would be appreciated. thank you in advance.

**Comment by zengjie617789** [comment]
I solved it by myself, and the reuslts is pretty well.

**Comment by shoutOutYangJie** [comment]
can you show some your result?

**Comment by zengjie617789** [comment]
@shoutOutYangJie .Here are test results below. As it shows, The aberration around face is obvious. Furthermore, the size of reference image influence the results a lot.
original image:
![image](https://github.com/InstantID/InstantID/assets/25050291/47e69ff9-d4f0-4824-a927-753725623f49)
results:
![image](https://github.com/InstantID/InstantID/assets/25050291/110411f4-6d22-4c9d-aa02-19601c5c84ca)

It need a further  improvement and i think img2img pipeline is in need.

**Comment by zengjie617789** [comment]
@shoutOutYangJie .Here are test results below. As it shows, The aberration around face is obvious. Furthermore, the size of reference image influence the results a lot.
original image:
![image](https://github.com/InstantID/InstantID/assets/25050291/47e69ff9-d4f0-4824-a927-753725623f49)
results:
![image](https://github.com/InstantID/InstantID/assets/25050291/110411f4-6d22-4c9d-aa02-19601c5c84ca)

It need a further  improvement and i think img2img pipeline is in need.

**Comment by tg-bomze** [comment]
> @shoutOutYangJie .Here are test results below. As it shows, The aberration around face is obvious. Furthermore, the size of reference image influence the results a lot. original image: ![image](https://private-user-images.githubusercontent.com/25050291/301732469-47e69ff9-d4f0-4824-a927-753725623f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MzI1MjUsIm5iZiI6MTcwODUzMjIyNSwicGF0aCI6Ii8yNTA1MDI5MS8zMDE3MzI0NjktNDdlNjlmZjktZDRmMC00ODI0LWE5MjctNzUzNzI1NjIzZjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE2MTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0OTJmYjg5NmIyYmFlYzk1YzgzMjE3ZjhmYTcyNDNmYjRiM2NlNGQ1YTMzNTUxZjVkMDVkMWM3MWIxMzVmZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MWNyyad65TBJKveNGyRVAp3tcoeR-QrWUpZVc9H-Vgo) results: ![image](https://private-user-images.githubusercontent.com/25050291/301732503-110411f4-6d22-4c9d-aa02-19601c5c84ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MzI1MjUsIm5iZiI6MTcwODUzMjIyNSwicGF0aCI6Ii8yNTA1MDI5MS8zMDE3MzI1MDMtMTEwNDExZjQtNmQyMi00YzlkLWFhMDItMTk2MDFjNWM4NGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE2MTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZDhkM2RmM2MzZWZkYzMzYTgxMDdmMmY3ODUxYzZkOWM2NTM3OTQzMGIxMTUyNzIwYzAxODI1Zjg0NmZmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZIdDN78RUIyKYQelsmdQTwHZllOWcZzyaRLLYX35-U8)
> 
> It need a further improvement and i think img2img pipeline is in need.

That's a cool result. Could you please share the code of the inpainting pipelines?

**Comment by zengjie617789** [comment]
I'm sorry I response this so late, because I didnt satisfied with my implement of this, and I finally use [this code](https://github.com/nosiu/InstantID-faceswap/blob/main/pipeline_stable_diffusion_xl_instantid_inpaint.py) to reach my goal;
Furthermore, If use sdxl-inpainting-1.0 model,  the  more smooth the results you got.

Here are my results below:
![2024-06-13_10-21-39](https://github.com/InstantID/InstantID/assets/25050291/95ae126d-c8b9-41b9-9b95-d4345e05a655)
![2024-06-13_10-24-12](https://github.com/InstantID/InstantID/assets/25050291/3d9e18e1-2d7a-401a-8cbd-f74a90ec6c77)
