### ISSUE TITLE
How to load LoRA in infer.py？

### ISSUE THREAD

**Issue by fanghao123-qw** [InstantID/InstantID#116]
When I try to load the LoRA model in infer.py using pipe.load_lora_weights(lora_model), I always encounter an error regarding mismatched dimensions. The complete error message is as follows:

RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for down_blocks.1.attentions.0.proj_in.lora_A.default_0.weight: copying a param with shape torch.Size([64, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for down_blocks.1.attentions.0.proj_in.lora_B.default_0.weight: copying a param with shape torch.Size([640, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for down_blocks.1.attentions.0.proj_out.lora_A.default_0.weight: copying a param with shape torch.Size([64, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for down_blocks.1.attentions.0.proj_out.lora_B.default_0.weight: copying a param with shape torch.Size([640, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for down_blocks.1.attentions.1.proj_in.lora_A.default_0.weight: copying a param with shape torch.Size([64, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for down_blocks.1.attentions.1.proj_in.lora_B.default_0.weight: copying a param with shape torch.Size([640, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for down_blocks.1.attentions.1.proj_out.lora_A.default_0.weight: copying a param with shape torch.Size([64, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for down_blocks.1.attentions.1.proj_out.lora_B.default_0.weight: copying a param with shape torch.Size([640, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for down_blocks.2.attentions.0.proj_in.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 1280]).
        size mismatch for down_blocks.2.attentions.0.proj_in.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 64]).
        size mismatch for down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_k.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_v.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for down_blocks.2.attentions.0.proj_out.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 1280]).
        size mismatch for down_blocks.2.attentions.0.proj_out.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 64]).
        size mismatch for down_blocks.2.attentions.1.proj_in.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 1280]).
        size mismatch for down_blocks.2.attentions.1.proj_in.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 64]).
        size mismatch for down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_k.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_v.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for down_blocks.2.attentions.1.proj_out.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 1280]).
        size mismatch for down_blocks.2.attentions.1.proj_out.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 64]).
        size mismatch for up_blocks.1.attentions.0.proj_in.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.0.proj_in.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_q.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_q.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_k.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_k.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_v.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_v.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_out.0.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn1.to_out.0.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_q.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_q.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.ff.net.0.proj.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.ff.net.0.proj.lora_B.default_0.weight: copying a param with shape torch.Size([10240, 64]) from checkpoint, the shape in current model is torch.Size([5120, 64]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.ff.net.2.lora_A.default_0.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([64, 2560]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.ff.net.2.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.0.proj_out.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.0.proj_out.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.1.proj_in.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.1.proj_in.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_q.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_q.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_k.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_k.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_v.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_v.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_out.0.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn1.to_out.0.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_q.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_q.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_out.0.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_out.0.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.ff.net.0.proj.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.ff.net.0.proj.lora_B.default_0.weight: copying a param with shape torch.Size([10240, 64]) from checkpoint, the shape in current model is torch.Size([5120, 64]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.ff.net.2.lora_A.default_0.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([64, 2560]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.ff.net.2.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.1.proj_out.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.1.proj_out.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.2.proj_in.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.2.proj_in.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_q.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_q.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_k.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_k.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_v.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_v.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_out.0.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_out.0.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_q.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_q.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_k.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_k.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_v.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_v.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_out.0.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_out.0.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.ff.net.0.proj.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.ff.net.0.proj.lora_B.default_0.weight: copying a param with shape torch.Size([10240, 64]) from checkpoint, the shape in current model is torch.Size([5120, 64]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.ff.net.2.lora_A.default_0.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([64, 2560]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.ff.net.2.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for up_blocks.1.attentions.2.proj_out.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 640]).
        size mismatch for up_blocks.1.attentions.2.proj_out.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 64]).
        size mismatch for mid_block.attentions.0.proj_in.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 1280]).
        size mismatch for mid_block.attentions.0.proj_in.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 64]).
        size mismatch for mid_block.attentions.0.transformer_blocks.0.attn2.to_k.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for mid_block.attentions.0.transformer_blocks.0.attn2.to_v.lora_A.default_0.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for mid_block.attentions.0.proj_out.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 1280]).
        size mismatch for mid_block.attentions.0.proj_out.lora_B.default_0.weight: copying a param with shape torch.Size([1280, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 64]).

**Comment by wangqixun** [comment]
兄弟你检查一下你的lora key吧，lora_A.default_0.weight 这种命名diffusers目前是不支持的好像

**Comment by wangqixun** [comment]
c站上下载一个lora试试。你是ucas的？

**Comment by fanghao123-qw** [comment]
> 兄弟你检查一下你的lora key吧，lora_A.default_0.weight 这种命名diffusers目前是不支持的好像

确实是lora的问题，我换了个转过diffuser的就好了。顺带一提，我是ucas的 :)

**Comment by wangqixun** [comment]
欢迎加群

![wecom-temp-201960-3eab9fd5e6b0f66034f5e56d2a3379b9](https://github.com/InstantID/InstantID/assets/46553287/908fd77d-a406-4e7b-8417-c601c0658b8a)

**Comment by cdong4676** [comment]
> 欢迎加群
> 
> ![wecom-temp-201960-3eab9fd5e6b0f66034f5e56d2a3379b9](https://private-user-images.githubusercontent.com/46553287/301786057-908fd77d-a406-4e7b-8417-c601c0658b8a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODA5MjksIm5iZiI6MTcwODY4MDYyOSwicGF0aCI6Ii80NjU1MzI4Ny8zMDE3ODYwNTctOTA4ZmQ3N2QtYTQwNi00ZTdiLTg0MTctYzYwMWMwNjU4YjhhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA5MzAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNGFiM2VmMjM5NDdiODc3MTQ1M2Q1NmY5ZDYxMDJkNmFjMmY5MDRlNGIzZGMwYTNmZmIyNjQwOWVlOGEwY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ea__fubXWICjIAqWH8zx2O8djARPBDDBCIAlBeyZh8)

可以再发一下群二维码吗？谢谢

**Comment by oftenliu** [comment]
> > 欢迎加群
> > ![wecom-temp-201960-3eab9fd5e6b0f66034f5e56d2a3379b9](https://private-user-images.githubusercontent.com/46553287/301786057-908fd77d-a406-4e7b-8417-c601c0658b8a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODA5MjksIm5iZiI6MTcwODY4MDYyOSwicGF0aCI6Ii80NjU1MzI4Ny8zMDE3ODYwNTctOTA4ZmQ3N2QtYTQwNi00ZTdiLTg0MTctYzYwMWMwNjU4YjhhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA5MzAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNGFiM2VmMjM5NDdiODc3MTQ1M2Q1NmY5ZDYxMDJkNmFjMmY5MDRlNGIzZGMwYTNmZmIyNjQwOWVlOGEwY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ea__fubXWICjIAqWH8zx2O8djARPBDDBCIAlBeyZh8)
> 
> 可以再发一下群二维码吗？谢谢

能拉我入群么

**Comment by SongDaShuai** [comment]
> 欢迎加群
> 
> ![wecom-temp-201960-3eab9fd5e6b0f66034f5e56d2a3379b9](https://private-user-images.githubusercontent.com/46553287/301786057-908fd77d-a406-4e7b-8417-c601c0658b8a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTQ5ODMsIm5iZiI6MTcxMzI1NDY4MywicGF0aCI6Ii80NjU1MzI4Ny8zMDE3ODYwNTctOTA4ZmQ3N2QtYTQwNi00ZTdiLTg0MTctYzYwMWMwNjU4YjhhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA4MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMjY0Njg3OTA1ZWI1YWU2NDY3Y2U5MzNkOGY0MjI1MzMwYjBkZjU4ZWM4M2FiODEzYmViYjA3M2Q1ODgyOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sI7QiLWFRTf3KYWspIlzRgjKGrP-vg35vgPzXXFMiFg)

能拉我进群吗
