### ISSUE TITLE
InstantID for full body.

### ISSUE THREAD

**Issue by ynie** [InstantID/InstantID#12]
Hello, thanks for the project. I’m currently using aipadapter to generate the same character(same face + outfit) with different pose, and I’m wondering if instantID would be a better choice. From the examples, it seems like this is for portrait only. Am I right? Thanks!

**Comment by wangqixun** [comment]
> Hello, thanks for the project. I’m currently using aipadapter to generate the same character(same face + outfit) with different pose, and I’m wondering if instantID would be a better choice. From the examples, it seems like this is for portrait only. Am I right? Thanks!

yes, the current version of InstantID is for portrait only. But we will release InstantAnything  and InstantPose soon. Maybe it can help you. Thank you for continuing to follow InstantID.

InstantPose case
<img width="1335" alt="image" src="https://github.com/InstantID/InstantID/assets/46553287/56a08764-2d56-4502-bd8a-fbfc9db7be2d">
<img width="1331" alt="image" src="https://github.com/InstantID/InstantID/assets/46553287/0a5d6e66-79c4-446e-87fb-701445494f2a">
![3a282ea3cd1274e2886c216764fc68a683dd0479a9dbb3b1c9602302](https://github.com/InstantID/InstantID/assets/46553287/65654ec9-8cad-4bfd-82b7-2373a6c06bf5)


InstantAnything case
<img width="1367" alt="image" src="https://github.com/InstantID/InstantID/assets/46553287/faa358a8-69bc-4066-ba3b-6b40e9d9567c">

<img width="1387" alt="image" src="https://github.com/InstantID/InstantID/assets/46553287/954781c1-8256-44b1-8bec-ba7b3ac9f7e3">

**Comment by ynie** [comment]
Thank you!

**Comment by hben35096** [comment]
Unbelievable, you mean that just openpose action sequence frames can animate the characters in the reference image?

**Comment by wangqixun** [comment]
> Unbelievable, you mean that just openpose action sequence frames can animate the characters in the reference image?

🤫

**Comment by Arcitec** [comment]
@wangqixun I am jsut here to say thank you. You are making history. I've never seen anything this impressive before! InstantPose and InstantAnything! Wow! Any idea when they are ready for release? Months? Year? :)

**Comment by hypervoxel** [comment]
@wangqixun I would also love Instantpose, I am trying to use InstantID with Openpose and it does not work well. Instantpose would be amazing!!

**Comment by hypervoxel** [comment]
> Hello, thanks for the project. I’m currently using aipadapter to generate the same character(same face + outfit) with different pose, and I’m wondering if instantID would be a better choice. From the examples, it seems like this is for portrait only. Am I right? Thanks!

I am also trying to do this! I found that InstantID doesn't work well with Openpose. Can I ask about your method? Are you using A1111 or Comfy?
