### ISSUE TITLE
 Inquiry Regarding InstantID's Integration with Pre-existing Architectures for Enhanced Flexibility

### ISSUE THREAD

**Issue by yihong1120** [InstantID/InstantID#13]
Dear InstantID Contributors,

I trust this message finds you well. I am reaching out to extend my commendations on the remarkable strides your team has made with the InstantID project. The innovative approach towards zero-shot identity-preserving generation is nothing short of impressive.

Having perused your technical report and examined the project's capabilities, I am keen to understand the potential for integrating InstantID with pre-existing neural network architectures. Specifically, I am curious about the following aspects:

1. **Compatibility and Adaptability**: Could you elucidate on how InstantID might interface with architectures beyond the mentioned SD1.5 and SDXL models? Are there any plans to support additional frameworks, and if so, which ones?

2. **Module Flexibility**: Given that InstantID operates as a plug-and-play module, what are the limitations when it comes to incorporating it with custom-designed neural networks? Are there specific architectural features or layers that are requisite for seamless integration?

3. **Performance Trade-offs**: When embedding InstantID into other architectures, have you observed any significant trade-offs in terms of generation quality or identity preservation fidelity?

I believe that a deeper understanding of these integration dynamics could significantly enhance the utility of InstantID for researchers and developers who may wish to leverage its capabilities within a broader spectrum of applications.

I eagerly anticipate your response and any insights you may be willing to share. Should you require further clarification on my queries, please do not hesitate to contact me.

Thank you for your time and the invaluable contributions your work represents to the field of AI-driven image generation.

Best regards,
yihong1120

**Comment by wangqixun** [comment]
Thank you very much for your question.

1.Due to the lack of open-source models from other companies and the lack of active community, we have only adapted to the SD series at this stage. We currently have no plans to adapt to non SD architectures. Sorry.

2.No, all InstantID need is diffusers. Applicable to all base model, lora, textual inversion, controlnet on civitai.com

3.We have not yet found any conflict issues between ID information and style. On some models, there is a color deepening problem caused by high ID weights. In this case, it's better to reduce the ID weight. Low ID weight still satisfies high ID consistency
<img width="1479" alt="image" src="https://github.com/InstantID/InstantID/assets/46553287/f44632ba-9f56-4786-ae66-10f7974cb158">

**Comment by a-r-r-o-w** [comment]
@wangqixun @haofanwang Thank you for your incredibly amazing work! It is very inspiring to see the progress you've made with this research, which is understandable even to someone newer in the field. You already provide a pipeline that works straightaway but I believe your technique can be applied directly for multiple tasks such as inpainting, video-generation with SD-backbone like AnimateDiff, etc. Do you have plans on integrating your method directly into a library like diffusers? I understand that insightface dependencies might be a limiting factor in the integration but maybe something with optional support can be included/proposed to the core team. It will allow for using your method easily on various tasks.

Once again, thank your for your time and contribution! It is my aspiration to work on such impressive ideas too as I improve my knowledge, and researchers like your team and all the ideas/papers that they write about are very motivating.

**Comment by ResearcherXman** [comment]
> @wangqixun @haofanwang Thank you for your incredibly amazing work! It is very inspiring to see the progress you've made with this research, which is understandable even to someone newer in the field. You already provide a pipeline that works straightaway but I believe your technique can be applied directly for multiple tasks such as inpainting, video-generation with SD-backbone like AnimateDiff, etc. Do you have plans on integrating your method directly into a library like diffusers? I understand that insightface dependencies might be a limiting factor in the integration but maybe something with optional support can be included/proposed to the core team. It will allow for using your method easily on various tasks.
> 
> Once again, thank your for your time and contribution! It is my aspiration to work on such impressive ideas too as I improve my knowledge, and researchers like your team and all the ideas/papers that they write about are very motivating.

Thank you very much for your attention!

We are integrating into diffusers to support other tasks like inpainting, video generation tasks. At the same time, we look forward to working with the community to make impactful contributions. Thank you very very much.

**Comment by haofanwang** [comment]
Working on diffusers integration at this moment. You can see our PR soon.
