### ISSUE TITLE
no file diffusion_pytorch_model.bin 

### ISSUE THREAD

**Issue by jifei** [InstantID/InstantID#130]
controlnet = ControlNetModel.from_pretrained(controlnet_path, torch_dtype=torch.float16)
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 634, in from_pretrained
    model_file = _get_model_file(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/utils/hub_utils.py", line 262, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory ./checkpoints/ControlNetModel.

**Comment by haofanwang** [comment]
Please make sure that you have downloaded the required models successfully.

**Comment by jifei** [comment]
https://huggingface.co/InstantX/InstantID/tree/main/ControlNetModel, there's diffusion_pytorch_model.safetensors but no diffusion_pytorch_model.bin

**Comment by jifei** [comment]
> Please make sure that you have downloaded the required models successfully.

In https://huggingface.co/InstantX/InstantID/tree/main/ControlNetModel, there's diffusion_pytorch_model.safetensors but no diffusion_pytorch_model.bin. Fully referenced README.md

**Comment by jontstaz** [comment]
I'm facing the same error. I tried converting it to a bin but then it throws errors relating to weights, etc.

**Comment by gagbaghdas** [comment]
Starting from today, I'm facing the same issue guys. Why is it trying to use the ```.bin``` instead of ```.safetensors``` ? Before it used ```.safetensors``` .

**Comment by gagbaghdas** [comment]
ok, I found the problem. It comes from the ```diffusion_pytorch_model.safetensors``` file, something is wrong with the file. In my case, I've downloaded it using the hub downloaded , which put the model into hugging face cache, and created a symlink , and it didn't work , as I tried to run my project with docker , which means that the symlink pointed to the directory outside from the docker.

**Comment by JohnCarpenter2** [comment]
I meet the same issue. Has anyone find quick methods to fix this?
```
OSError: Error no file named diffusion_pytorch_model.bin found in directory ./checkpoints/ControlNetModel.
```

**Comment by gagbaghdas** [comment]
> I meet the same issue. Has anyone find quick methods to fix this?
> 
> ```
> OSError: Error no file named diffusion_pytorch_model.bin found in directory ./checkpoints/ControlNetModel.
> ```

Check your ```diffusion_pytorch_model.safetensors``` file. Check it's size and actual location.

**Comment by JohnCarpenter2** [comment]
> > I meet the same issue. Has anyone find quick methods to fix this?
> > ```
> > OSError: Error no file named diffusion_pytorch_model.bin found in directory ./checkpoints/ControlNetModel.
> > ```
> 
> Check your `diffusion_pytorch_model.safetensors` file. Check it's size and actual location.

Thanks a lot. The bug is fixed. @gagbaghdas

**Comment by yves00255** [comment]
> I meet the same issue. Has anyone find quick methods to fix this?
> 
> ```
> OSError: Error no file named diffusion_pytorch_model.bin found in directory ./checkpoints/ControlNetModel.
> ```
I meet the same error and make sure it is in correct file 
![image](https://github.com/user-attachments/assets/c8f2acbd-aa29-4af1-853c-dcd9c2afb62b)
Error no file named diffusion_pytorch_model.bin found in directory D:\ComfyUI\ComfyUI\models\CogVideo\CogVideoX-5b-1.5.

**Comment by simp6969** [comment]
but how?

**Comment by lakshya247** [comment]
> I'm facing the same error. I tried converting it to a bin but then it throws errors relating to weights, etc.

what does it mean y weights in it

**Comment by lakshya247** [comment]
> > I meet the same issue. Has anyone find quick methods to fix this?
> > ```
> > OSError: Error no file named diffusion_pytorch_model.bin found in directory ./checkpoints/ControlNetModel.
> > ```
> 
> Check your `diffusion_pytorch_model.safetensors` file. Check it's size and actual location.

actually it's not that simple it's asking for the .bin file and I didn't found the .bin file
