### ISSUE TITLE
Would a cropped face have better fidelity or not?

### ISSUE THREAD

**Issue by machineminded** [InstantID/InstantID#131]
I have some images of my face that are very cropped - meaning you can't see hairline, ears, etc.  But these images do not work with InstantID.  Is it preferred to use further zoomed out photos?  Would we gain fidelity from using heavily cropped face images?

I see this error often:

```
    face_info = sorted(face_info, key=lambda x:(x['bbox'][2]-x['bbox'][0])*x['bbox'][3]-x['bbox'][1])[-1]  # only use the maximum face
IndexError: list index out of range
```

**Comment by haofanwang** [comment]
We don't suggest using very cropped image, because face detector may not find a face. It actually does not matter, the face will automatically detect and crop before extracting features.
