### ISSUE TITLE
Join Huggingface x InstantID Spring Festival Event

### ISSUE THREAD

**Issue by haofanwang** [InstantID/InstantID#133]
Hi, all, we are the team from InstantX

We are co-organizing a Spring Festival event with HuggingFace from 2024.2.7 to 2024.2.25. You can now generate pictures of Spring Festival costumes on our [official web demo](https://huggingface.co/spaces/InstantX/InstantID) now, we have prepared a default spring festival style for you, but we do encourage you to try on your own (prompts, base models or any other idea). The [Spring Festival](https://en.wikipedia.org/wiki/Chinese_New_Year) is a festival that celebrates the beginning of a new year on the traditional lunisolar Chinese calendar, and more importantly, it is a time for family, for reunion.

Our event is holding on [Xiaohongshu](https://www.xiaohongshu.com/explore) platform, generate your image with spring festival costumes, post it with event hashtag, follow the account of HuggingFace and @Huggingface. We will pick out some lucky guys to send our official festival gifts based on number of likes, quality of post, etc. More details can be found on the [official event page](https://www.xiaohongshu.com/explore/65c35b4b000000002c012ee0). If you have any question, please feel free to reach us out.

Last but not least, Happy Chinese New Year! Happy Lunar New Year! Don’t forget to tell your family how much you ❤️ them!

**Comment by wangqixun** [comment]
from InstantX！！！

**Comment by cqflgl** [comment]
thanks for your great job！ Happy Chinese New Year!

**Comment by taoisu** [comment]
Happy Chinese New Year!

Can you share the styles for "Spring Festial"? Wanna run it locally, demo page has quota for GPU which runs out very quickly.

**Comment by taoisu** [comment]
It seems the huggingface space demo is much better in terms of following instructions, anything you can share?

**Comment by haofanwang** [comment]
The default style template is "Flat illustration, a Chinese {prompt}, ancient style, wearing a red cloth, smile face, white skin, clean background, fireworks blooming, red lanterns". You can play it with your own idea. I do hope you enjoy it!
