### ISSUE TITLE
question about how to control expression?

### ISSUE THREAD

**Issue by cavalier501** [InstantID/InstantID#142]
Thank you for your work, but I have some inquiries regarding facial expression control about instantID.

In your work, it seems that the face embedding only provides identity information of the face in the reference image, lacking facial expression details. On the other hand, landmarks only consist of five key points, offering limited spatial control.

I wonder: How does InstantID manage to maintain consistency between the facial expressions in the output image and the reference image?

Thanks.

**Comment by haofanwang** [comment]
Actually, we don't want to constrain and fix the facial expression as the same as the given image. That is why we only use 5 kpts. As for your concern, you can adopt another facial pose controlnet to control the detail of face.

**Comment by cavalier501** [comment]
> Actually, we don't want to constrain and fix the facial expression as the same as the given image. That is why we only use 5 kpts. As for your concern, you can adopt another facial pose controlnet to control the detail of face.

Thanks much for your answer.
