### ISSUE TITLE
question about compatibility of IdentityNet

### ISSUE THREAD

**Issue by cavalier501** [InstantID/InstantID#143]
Thanks very much for your work. I'm very interested and have some questions regarding the compatibility of IdentityNet.

I noticed that your IdentityNet employs a structure similar to ControlNet. However, ControlNet cannot be directly transferred between models. In your work, Stable Diffusion is used as the foundation for the text-to-image model, can IdentityNet be directly applied to structures like SD1.5 or GLIDE after training?

I would appreciate more information on this matter and express sincere gratitude for your contributions in this field.

**Comment by haofanwang** [comment]
No, ControlNet and IdentityNet are both copied from UNet. Thus, as our released model is trained on SDXL, it can only be adopted to SDXL based models.

**Comment by cavalier501** [comment]
> No, ControlNet and IdentityNet are both copied from UNet. Thus, as our released model is trained on SDXL, it can only be adopted to SDXL based models.

Thanks much for your answer.
