### ISSUE TITLE
normal vs full pipeline differences?

### ISSUE THREAD

**Issue by felixsanz** [InstantID/InstantID#155]
There are 2 pipeline files:

- pipeline_stable_diffusion_xl_instantid.py
- pipeline_stable_diffusion_xl_instantid_full.py

What is the difference? i diffed the files but can't spot what's going on. thanks

**Comment by ResearcherXman** [comment]
The first file is simplest code of our work. In the second file, we further show you how to combine our work with existing ControlNets and support for long prompt input.
