### ISSUE TITLE
where the base_model?

### ISSUE THREAD

**Issue by invade-art** [InstantID/InstantID#176]
i want to download the base_model in my local.and how to use it

**Comment by wangqixun** [comment]
https://civitai.com/models/84040/sdxl-unstable-diffusers-yamermix?modelVersionId=309729

**Comment by invade-art** [comment]
![734e1646c3865fdb3e2d2a2f183e669](https://github.com/InstantID/InstantID/assets/84616698/4370d51b-5ebc-431d-b7af-be2b0056d45a)

**Comment by invade-art** [comment]
OSError: Cannot load model anything-v5-PrtRE.safetensors: model is not cached locally and an error occured while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.

**Comment by invade-art** [comment]
T.T

**Comment by invade-art** [comment]
老哥，这个怎么解决呀，模型下载到本地时有这个问题。

**Comment by wangqixun** [comment]
下载到本地即可，或者下载这个https://huggingface.co/wangqixun/YamerMIX_v8

**Comment by invade-art** [comment]
我上面那个图那种做法对吗，为啥会报错

**Comment by xuyu666** [comment]
我也是，从抱脸下的YamerMIX_v8包含unet、VAE等组件，替换路径可以用。
但后来从c站下6个G的safetensor，不知道怎么在权重列表替换。尝试用下载好的safetensor替换Unet文件夹中的safetensor（模型路径保持不变），但跑起来貌似权重不匹配，作者能教教我么。
![image](https://github.com/InstantID/InstantID/assets/49869475/e9929014-323b-4d6e-806d-0898722bfd02)
![image](https://github.com/InstantID/InstantID/assets/49869475/d62706ca-c334-43e7-8c4f-50ad3cff058c)

**Comment by liuxuan111** [comment]
> 我也是，从抱脸下的YamerMIX_v8包含unet、VAE等组件，替换路径可以用。 但后来从c站下6个G的safetensor，不知道怎么在权重列表替换。尝试用下载好的safetensor替换Unet文件夹中的safetensor（模型路径保持不变），但跑起来貌似权重不匹配，作者能教教我么。 ![image](https://private-user-images.githubusercontent.com/49869475/311419164-e9929014-323b-4d6e-806d-0898722bfd02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDI0MTIsIm5iZiI6MTcxMDE0MjExMiwicGF0aCI6Ii80OTg2OTQ3NS8zMTE0MTkxNjQtZTk5MjkwMTQtMzIzYi00ZDZlLTgwNmQtMDg5ODcyMmJmZDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA3MjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NjNkMjQ4NmI3NDJhOTYyOGRjZTYwMWVkYmU2OTM2MDJmZTBlMjYzZjQzNmQ4MDRmMmY0N2NiOTY4OGY2NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lEaSkX2NDaoWjpKQlckHd3y7nyhT0WnNTJ2Ygg4QiJY) ![image](https://private-user-images.githubusercontent.com/49869475/311418966-d62706ca-c334-43e7-8c4f-50ad3cff058c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDI0MTIsIm5iZiI6MTcxMDE0MjExMiwicGF0aCI6Ii80OTg2OTQ3NS8zMTE0MTg5NjYtZDYyNzA2Y2EtYzMzNC00M2U3LThjNGYtNTBhZDNjZmYwNThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA3MjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZDU2MDBiZGNlNDg2ZTNiYjIyMGQ5YzRjNDNhNWFjOWY0OTQyMGU0NWFmNTUzZDdmNDM0OGRmMmIwZDQxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZcrifXccDYm_PX3lkxHPB7CEPPEubMCnAMVg5iB1mg)

我在其他地方看到单个.safetensor，可以用.from_single_file而不是.from_pretrained，但是我从来没成功过
参考 https://huggingface.co/docs/diffusers/v0.26.3/en/api/loaders/single_file#diffusers.loaders.FromSingleFileMixin.from_single_file.example
