### ISSUE TITLE
ImportError: cannot import name 'IPAttnProcessor2_0' from 'ip_adapter.attention_processor'

### ISSUE THREAD

**Issue by whiterose199187** [InstantID/InstantID#18]
Hi, 

Trying the demo, looks like a bug here? 

```
ImportError                               Traceback (most recent call last)

[<ipython-input-12-eeef1f01030c>](https://localhost:8080/#) in <cell line: 11>()
      9 
     10 from insightface.app import FaceAnalysis
---> 11 from pipeline_stable_diffusion_xl_instantid import StableDiffusionXLInstantIDPipeline, draw_kps

[/content/InstantID/pipeline_stable_diffusion_xl_instantid.py](https://localhost:8080/#) in <module>
     47         AttnProcessor2_0 as AttnProcessor,
     48     )
---> 49     from ip_adapter.attention_processor import (
     50         IPAttnProcessor2_0 as IPAttnProcessor,
     51     )

ImportError: cannot import name 'IPAttnProcessor2_0' from 'ip_adapter.attention_processor' (/content/InstantID/ip_adapter/attention_processor.py
```

**Comment by ResearcherXman** [comment]
Is everything ok? @whiterose199187

**Comment by whiterose199187** [comment]
yes, this error is fixed

**Comment by whiterose199187** [comment]
```
RuntimeError: Could not infer dtype of NoneType
```

Getting this error on line:  images = pipe(prompt, image_embeds=face_emb, image=face_kps, controlnet_conditioning_scale=0.8).images

**Comment by ResearcherXman** [comment]
What is the input image? It seems that the face model cannot find a face from it, and the face_emb is None. Try another image.

**Comment by whiterose199187** [comment]
```1

---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

[<ipython-input-55-66e60fe9245f>](https://localhost:8080/#) in <cell line: 7>()
      5 print(len(face_info))
      6 face_info = sorted(face_info, key=lambda x:(x['bbox'][2]-x['bbox'][0])*x['bbox'][3]-x['bbox'][1])[-1] # only use the maximum face
----> 7 face_emb = face_info['embedding']
      8 # face_emb = face_info.normed_embedding
      9 print(face_emb)

KeyError: 'embedding'
```

This is the error when running the below snippet:

```
# load an image
face_image = load_image("https://m.media-amazon.com/images/M/MV5BODg3MzYwMjE4N15BMl5BanBnXkFtZTcwMjU5NzAzNw@@._V1_FMjpg_UX1000_.jpg")
# prepare face emb
face_info = app.get(cv2.cvtColor(np.array(face_image), cv2.COLOR_RGB2BGR))
print(len(face_info))
face_info = sorted(face_info, key=lambda x:(x['bbox'][2]-x['bbox'][0])*x['bbox'][3]-x['bbox'][1])[-1] # only use the maximum face
face_emb = face_info['embedding']
# face_emb = face_info.normed_embedding
print(face_emb)
face_kps = draw_kps(face_image, face_info['kps'])
# face_kps.save('kps.jpg')
pipe.set_ip_adapter_scale(0.8)

prompt = "RAW photo, A portrait photograph of a woman aged between 21 and 35 as a renowned mixologist, crafting cocktails in a trendy Manhattan bar, 16k uhd, dslr, photorealistic, natural lighting, high quality, film grain, Fujifilm XT3"
negative_prompt = "(lowres, low quality, worst quality:1.2), (text:1.2), watermark, painting, drawing, illustration, glitch, deformed, mutated, cross-eyed, ugly, disfigured (lowres, low quality, worst quality:1.2), (text:1.2), watermark, painting, drawing, illustration, glitch,deformed, mutated, cross-eyed, ugly, disfigured"

# generate image
images = pipe(prompt, image_embeds=face_emb, image=face_kps, controlnet_conditioning_scale=0.8).images
```

**Comment by wangqixun** [comment]
> ```
> ---------------------------------------------------------------------------
> 
> KeyError                                  Traceback (most recent call last)
> 
> [<ipython-input-55-66e60fe9245f>](https://localhost:8080/#) in <cell line: 7>()
>       5 print(len(face_info))
>       6 face_info = sorted(face_info, key=lambda x:(x['bbox'][2]-x['bbox'][0])*x['bbox'][3]-x['bbox'][1])[-1] # only use the maximum face
> ----> 7 face_emb = face_info['embedding']
>       8 # face_emb = face_info.normed_embedding
>       9 print(face_emb)
> 
> KeyError: 'embedding'
> ```
> 
> This is the error when running the below snippet:
> 
> ```
> # load an image
> face_image = load_image("https://m.media-amazon.com/images/M/MV5BODg3MzYwMjE4N15BMl5BanBnXkFtZTcwMjU5NzAzNw@@._V1_FMjpg_UX1000_.jpg")
> # prepare face emb
> face_info = app.get(cv2.cvtColor(np.array(face_image), cv2.COLOR_RGB2BGR))
> print(len(face_info))
> face_info = sorted(face_info, key=lambda x:(x['bbox'][2]-x['bbox'][0])*x['bbox'][3]-x['bbox'][1])[-1] # only use the maximum face
> face_emb = face_info['embedding']
> # face_emb = face_info.normed_embedding
> print(face_emb)
> face_kps = draw_kps(face_image, face_info['kps'])
> # face_kps.save('kps.jpg')
> pipe.set_ip_adapter_scale(0.8)
> 
> prompt = "RAW photo, A portrait photograph of a woman aged between 21 and 35 as a renowned mixologist, crafting cocktails in a trendy Manhattan bar, 16k uhd, dslr, photorealistic, natural lighting, high quality, film grain, Fujifilm XT3"
> negative_prompt = "(lowres, low quality, worst quality:1.2), (text:1.2), watermark, painting, drawing, illustration, glitch, deformed, mutated, cross-eyed, ugly, disfigured (lowres, low quality, worst quality:1.2), (text:1.2), watermark, painting, drawing, illustration, glitch,deformed, mutated, cross-eyed, ugly, disfigured"
> 
> # generate image
> images = pipe(prompt, image_embeds=face_emb, image=face_kps, controlnet_conditioning_scale=0.8).images
> ```

It may be an issue with your environment. I test it. It's normal

![image](https://github.com/InstantID/InstantID/assets/46553287/8ebd2aad-6ac7-4f6a-8c10-9ae0170fcaa1)
