### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)

### ISSUE THREAD

**Issue by water2015sit** [InstantID/InstantID#200]
When I am trying to run the following command to download all models, it shows an error like this: 
<img width="378" alt="image" src="https://github.com/InstantID/InstantID/assets/47031169/0e4f34f8-7f82-4513-b511-a00be278469a">
<img width="706" alt="image" src="https://github.com/InstantID/InstantID/assets/47031169/3755b931-a1ad-44c5-979f-a47b001a7990">
I searched the website and couldn't solve it.

**Comment by jkl375** [comment]
> When I am trying to run the following command to download all models, it shows an error like this: <img alt="image" width="378" src="https://private-user-images.githubusercontent.com/47031169/316360098-0e4f34f8-7f82-4513-b511-a00be278469a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDAxNDAsIm5iZiI6MTcxMTQzOTg0MCwicGF0aCI6Ii80NzAzMTE2OS8zMTYzNjAwOTgtMGU0ZjM0ZjgtN2Y4Mi00NTEzLWI1MTEtYTAwYmUyNzg0NjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA3NTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYjUwM2IxNDUzYjczMDdjMTQwNGJiM2Y3Y2RlZmM3ZjM4ZDY1ZDNiZDBhMDgyOGMzZGFmNDI5MTM1MGZjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.udPUcnErWGNAic4i73k9R5r9fG4l5_cGTI10GHCiykE"> <img alt="image" width="706" src="https://private-user-images.githubusercontent.com/47031169/316360151-3755b931-a1ad-44c5-979f-a47b001a7990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDAxNDAsIm5iZiI6MTcxMTQzOTg0MCwicGF0aCI6Ii80NzAzMTE2OS8zMTYzNjAxNTEtMzc1NWI5MzEtYTFhZC00NGM1LTk3OWYtYTQ3YjAwMWE3OTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA3NTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmM2U4MDI1YmFkM2FkZDI4ZjBlODI2YjkyMDdmNTQ5MTM2ZTJmOTg5OGUzOTE1ZjhjNjMzYzRjYTEwMjI2ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PbvT9rRjI_vgAOGBoed4-BA7eClJf34r3J3npgkr4KI"> I searched the website and couldn't solve it.

`pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
`

**Comment by water2015sit** [comment]
Thanks. I tried, but still get this error.
<img width="997" alt="image" src="https://github.com/InstantID/InstantID/assets/47031169/0f559391-49c8-4601-8d1b-636a7123bdd5">

**Comment by jkl375** [comment]
> Thanks. I tried, but still get this error. <img alt="image" width="997" src="https://private-user-images.githubusercontent.com/47031169/317085081-0f559391-49c8-4601-8d1b-636a7123bdd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTY3NjIsIm5iZiI6MTcxMTUxNjQ2MiwicGF0aCI6Ii80NzAzMTE2OS8zMTcwODUwODEtMGY1NTkzOTEtNDljOC00NjAxLThkMWItNjM2YTcxMjNiZGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA1MTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NzRhZTIxOWEzZTczZTdjNDdlMjk1OGZhMTU2YTk5ZTU4NmVkYWQxMDAwZWM4ZmFmNWRlZjFhMWNjNTA2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ml4eqFvpP00nLpsT_Q-B5NG-NGT8j7w9Gs4fpYMqevw">

You need to first confirm your cuda version is 11.x or later and uninstall your current version of onnxruntime-gpu. If it is cuda11
```
pip install onnxruntime gpu
```
If it is cuda12
```
pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
```

**Comment by water2015sit** [comment]
It works. Thank you!

**Comment by zArvin6808** [comment]
pip install torch==2.4.1+cu118 torchvision==0.19.1+cu118 torchaudio==2.4.1+cu118 --index-url https://download.pytorch.org/whl/cu118

pip install onnxruntime-gpu==1.18.0
我是降级安装
