### ISSUE TITLE
A problem with diffusers 0.27.3

### ISSUE THREAD

**Issue by wjkoh** [InstantID/InstantID#204]
Without any code modifications, upgrading from diffsusers version 0.26 to 0.27 results in the following error:

```
Exception occurred: For a single controlnet, `controlnet_conditioning_scale` must be of type `float`.
```

The data type for `controlnet_conditioning_scale` is float, yet the error persists even when a `1.0` float literal is provided. Could you please provide guidance on how to resolve this issue?

**Comment by wjkoh** [comment]
This fix seems related: https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/pull/124

**Comment by haofanwang** [comment]
Yes, this is because the latest version of the diffuser has some changes on the number of input params. We will make a update soon.

**Comment by ResearcherXman** [comment]
Solved.
