### ISSUE TITLE
VRAM requirement

### ISSUE THREAD

**Issue by rupeshs** [InstantID/InstantID#21]
Nice work,how much VRAM required for this?

**Comment by haofanwang** [comment]
24GB VRAM is suggested. But you can use some techniques for optimization, such as xformer.

**Comment by rupeshs** [comment]
@haofanwang thanks

**Comment by FurkanGozukara** [comment]
> 24GB VRAM is suggested. But you can use some techniques for optimization, such as xformer.

how do we use it?
