### ISSUE TITLE
Multiple input images - what to do with face_kps?

### ISSUE THREAD

**Issue by albusdemens** [InstantID/InstantID#213]
Hello, congrats for the great work! I'm trying to modify the demo app (`app.py`) so that it can take as input multiple images. 
- For `face_emb`, I plan to consider the average of the face embeddings from different images
- For `face_kps`, I am confused about what to do. Considering the line `face_kps = draw_kps(convert_from_cv2_to_image(face_image_cv2), face_info['kps'])`, how can I extend it to deal with multiple input images? As `face_info['kps']` I could consider the average of the kps values, but what about `face_image_cv2`? Thank you!

**Comment by haofanwang** [comment]
You can just select one image to extract keypoints.

**Comment by albusdemens** [comment]
That's exactly what I implemented ;-) Thanks for your reply!
