### ISSUE TITLE
SD3 Version?

### ISSUE THREAD

**Issue by Oguzhanercan** [InstantID/InstantID#256]
Are you gonna train it for SD3?

**Comment by haofanwang** [comment]
No support for SD3. But SD3.1 is on our todo list.

**Comment by jordancoult** [comment]
SD3 is not worth it IMO - I'd prefer it is skipped to prioritize Flux

**Comment by Oguzhanercan** [comment]
SD3 and flux literally same model. The difference is stability ai does not share big model publicly. Look at the writers of SD3 paper and founders of black forest labs. The problem with sd3 medium can be solved with strong guidance, weak to strong training (Pixart alfa, pixart sigma), which InstantID is able to do (To be honest , InstantID adds to much unnecessary params with controlnet, control can be done with ControlNext style technique but still it is the sota). Plus, a good trained lcm lora would fixes the trajectory and aligns the steps. So training InstantID for SD3 or 3.1 or flux whatsoever (the thing matters right here is the data seen by model, num of params and the architecture) probably will be end up with similar generation capacity.
