### ISSUE TITLE
sdxl instaintID Watermark in image

### ISSUE THREAD

**Issue by MATEMATNKx** [InstantID/InstantID#280]
![IMG_7032 jpg_result](https://github.com/user-attachments/assets/5a2d719d-efd4-4ede-abb8-1f28d5a74c4a)
How to fix it?

**Comment by Zibbibbo** [comment]
just don't generate at 1024x1024 size.
i usually stick on 904x1096 or viceversa wheni want to stay close to a square and eventually i crop the image later, btw the watermark fix is just to stay away from 1024x1024
