### ISSUE TITLE
ModuleNotFoundError: No module named 'pipeline_stable_diffusion_xl_instantid'

### ISSUE THREAD

**Issue by protector131090** [InstantID/InstantID#36]
(venv) S:\InstantID>python gradio_demo/app.py
Traceback (most recent call last):
  File "S:\InstantID\gradio_demo\app.py", line 19, in <module>
    from pipeline_stable_diffusion_xl_instantid import StableDiffusionXLInstantIDPipeline
ModuleNotFoundError: No module named 'pipeline_stable_diffusion_xl_instantid'

**Comment by zewolf5** [comment]
Its looking for the python code files. You can probably just copy the *.py + the ip_adapter from the parent folder into the gradio_demo folder.

**Comment by protector131090** [comment]
> Its looking for the python code files. You can probably just copy the *.py + the ip_adapter from the parent folder into the gradio_demo folder.

i copyed all form gradio folder to hte main folder and now it started to download some big files. But i get error AssertionError: Torch not compiled with CUDA enabled

**Comment by haofanwang** [comment]
You should make sure CUDA is available in your envs. In the demo code, the model is running on GPUs.

**Comment by zewolf5** [comment]
pip uninstall torch
pip install torch==2.0.0+cu117 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by hben35096** [comment]
Put app.py and style_template.py
Move to S:InstantID, and execute:
python app.py
![image](https://github.com/InstantID/InstantID/assets/139383150/8d109acb-8094-448e-abd1-3b54e72c0d77)
![image](https://github.com/InstantID/InstantID/assets/139383150/f48cf3b5-3c8c-4483-879a-e0a946eaa6a9)

**Comment by ResearcherXman** [comment]
Will fix it soon.

**Comment by ResearcherXman** [comment]
Tested locally. It should work now. @protector131090

**Comment by ResearcherXman** [comment]
Closed. Feel free to re-open if you still meet problems.

**Comment by andymacool** [comment]
can I run this locally on Mac M1 without GPU ? just for testing purpose, thanks !
