### ISSUE TITLE
antelopev2 not found in insightface releases

### ISSUE THREAD

**Issue by kovalexal** [InstantID/InstantID#38]
Hi @ResearcherXman!

Thank you and your team for such an interesting approach!

I was trying to use your inference code and found out that  `FaceAnalysis` model initialization for the `antelopev2` fails:

```
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip
```

Am I right, that the problem is on insightface side?
May I kindly ask you to share the weights of this model, while insightface team is trying to deal with download problem?

I created a corresponding issue in their repo https://github.com/deepinsight/insightface/issues/2517

**Comment by kovalexal** [comment]
@ruslanmustafin thanks for sharing the download link!

**Comment by haofanwang** [comment]
Thank you @ruslanmustafin. Actually, we provide the download url in README.md, please follow it carefully @kovalexal .

**Comment by kovalexal** [comment]
Thank you @haofanwang, my bad!

Closing this issue!

**Comment by jarod329** [comment]
> 看起来 Insightface 存储库的发行版页面中缺少它，但我能够[在这里](https://drive.google.com/file/d/18wEUfMNohBJ4K3Ly5wpTejPfDzp-8fI8/view)找到 antilopev2 的发行版。
> 
> 我下载了它，必须手动解压到 ./models 文件夹中。似乎正在按预期工作。



谢谢！找了半天也没找到，多亏了你！
