### ISSUE TITLE
Connection to huggingface.co timed out

### ISSUE THREAD

**Issue by Formyselfonly** [InstantID/InstantID#49]
No,I haven't enouth network speed!
it's directly by  this:"   base_model_path = 'wangqixun/YamerMIX_v8'   "

![image](https://github.com/InstantID/InstantID/assets/56914169/aef6a014-2dc7-4b79-87f3-0fd301997435)

**Comment by Formyselfonly** [comment]
Now i download manually
![image](https://github.com/InstantID/InstantID/assets/56914169/7369f29e-d074-45f5-ac96-f135a96d2039)


But i need to provide a model_index.json,how to write it or where to download?
![image](https://github.com/InstantID/InstantID/assets/56914169/baf92b81-c5f7-48aa-8478-e39b8d66083e)

**Comment by ResearcherXman** [comment]
It seems that you didn't download the model from [wangqixun/YamerMIX_v8](https://huggingface.co/wangqixun/YamerMIX_v8/tree/main), if you download `.safetensors` directly from other platforms, you have to convert it into diffusers format, then you will have a `.json`.

Regarding to connection problem, you can hf-mirror to download.

```
export HF_ENDPOINT=https://hf-mirror.com
huggingface-cli download --resume-download wangqixun/YamerMIX_v8 --local-dir base_model
```

**Comment by Formyselfonly** [comment]
> It seems that you didn't download the model from [wangqixun/YamerMIX_v8](https://huggingface.co/wangqixun/YamerMIX_v8/tree/main), if you download `.safetensors` directly from other platforms, you have to convert it into diffusers format, then you will have a `.json`.
> 
> Regarding to connection problem, you can hf-mirror to download.
> 
> ```
> export HF_ENDPOINT=https://hf-mirror.com
> huggingface-cli download --resume-download wangqixun/YamerMIX_v8 --local-dir base_model
> ```

Thank u bro!It works!
But now another problem in here:
KeyError: 'embedding'

There is the detail:
KeyError: 'embedding'
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/root/autodl-tmp/InstantID-main/gradio_demo/app.py", line 191, in generate_image
    face_emb = face_info['embedding']
KeyError: 'embedding'

**Comment by ResearcherXman** [comment]
What's your input image? It seems that the face model don't detect a face and return None.

**Comment by Formyselfonly** [comment]
> What's your input image? It seems that the face model don't detect a face and return None.
This is my input:
![image](https://github.com/InstantID/InstantID/assets/56914169/84204321-97b0-4fe7-9c32-65b538e558eb)

**Comment by ResearcherXman** [comment]
1. Is this your local gradio demo or our online demo?
2. Make sure you have downloaded the antelopev2 as your face model.

**Comment by Formyselfonly** [comment]
> 1. Is this your local gradio demo or our online demo?
> 2. Make sure you have downloaded the antelopev2 as your face model.

thanks,you're so kind!

**Comment by Formyselfonly** [comment]
It works!
![Uploading image.png…]()

**Comment by ResearcherXman** [comment]
Glad to know. Closed.
