### ISSUE TITLE
error when set num_images_per_prompt > 1

### ISSUE THREAD

**Issue by akk-123** [InstantID/InstantID#50]
@ResearcherXman  set set num_images_per_prompt > 1 will get error

```
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 2 for tensor number 1 in the list.
```

**Comment by ResearcherXman** [comment]
We will take a look.

**Comment by MarielMa** [comment]
没解决啊，仍然报错@ResearcherXman 
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2560 but got size 2048 for tensor number 1 in the list.

**Comment by wangqixun** [comment]
> 没解决啊，仍然报错@ResearcherXman RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2560 but got size 2048 for tensor number 1 in the list.

那就单图跑吧

**Comment by MarielMa** [comment]
我跑的就是单图，infer.py 不知道问题在哪
