### ISSUE TITLE
the result on my local machine is different from the result on the huggingface

### ISSUE THREAD

**Issue by haile-vnu** [InstantID/InstantID#52]
Thank you very much for your wonderful work!

I have a problem. I ran the code on my machine, I used the same image input and prompt, and the same seed, but I got a result different so much with the result on the hugging face
The left image is the result using your hugging face  https://huggingface.co/spaces/InstantX/InstantID
The right image is the result I got on the local machine
![image](https://github.com/InstantID/InstantID/assets/82585606/6a29c004-c9cf-47ec-a4bd-367b38467a4e)

Could you guess, where I got wrong? 

Thank you very much!

**Comment by wangqixun** [comment]
what is your base model, prompt, neg prompt?

**Comment by ResearcherXman** [comment]
Neither is expected. Please share more info with us.

**Comment by haile-vnu** [comment]
Hi @wangqixun , @ResearcherXman 

I used the prompt = "photo of a girl, long blonde hair", and the same n_prompt in the huggginig face
I used both base models
#base_model_path = 'wangqixun/YamerMIX_v8'
base_model_path = 'stabilityai/stable-diffusion-xl-base-1.0'

More details:

At first, I got an error TypeError: StableDiffusionXLControlNetPipeline.check_inputs() takes from 5 to 14                                                                                                     positional arguments but 15 were given for the file pipeline_stable_diffusion_xl_instantid.py
when I called the pipe, so I commented the self.check_inputs() command in this file
I also added:
self.clip_skip = clip_skip
self.cross_attention_kwargs = cross_attention_kwargs
self.do_classifier_free_guidance = False


Thank you very much!

**Comment by ResearcherXman** [comment]
Can you share your full infer script?

**Comment by haile-vnu** [comment]
I found the error is because my diffusers version is 0.23.0, I have upgraded the lib to 0.25.0 version. It is OK now.

Thank you very much for your wonderful work and support!
