### ISSUE TITLE
the name of the base model used on https://huggingface.co/spaces/InstantX/InstantID

### ISSUE THREAD

**Issue by haile-vnu** [InstantID/InstantID#57]
Hi,

Could you give the name of the base model used in the demo on
https://huggingface.co/spaces/InstantX/InstantID ?
It is  'wangqixun/YamerMIX_v8' or 'stabilityai/stable-diffusion-xl-base-1.0' model

Thank you very much!

**Comment by ResearcherXman** [comment]
We use "wangqixun/YamerMIX_v8" in our demo.

**Comment by haile-vnu** [comment]
Thank you for your infor!
