### ISSUE TITLE
Error when running gradio.py: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Exuan148** [InstantID/InstantID#67]
When I am running gradio.py, there is an error:

Traceback (most recent call last):
  File "gradio_demo/app.py", line 26, in <module>
    from model_util import load_models_xl, get_torch_device, torch_gc
  File "/home/yixuan/projects/InstantID-main/gradio_demo/model_util.py", line 167, in <module>
    ) -> tuple[CLIPTokenizer, CLIPTextModel, UNet2DConditionModel,]:
TypeError: 'type' object is not subscriptable

**Comment by ResearcherXman** [comment]
I believe there is a typo.

You should `from typing import Tuple`, and change `tuple[CLIPTokenizer, CLIPTextModel, UNet2DConditionModel,]` to `Tuple[CLIPTokenizer, CLIPTextModel, UNet2DConditionModel,]`. Please let me whether it works.

**Comment by Exuan148** [comment]
> I believe there is a typo.
> 
> You should `from typing import Tuple`, and change `tuple[CLIPTokenizer, CLIPTextModel, UNet2DConditionModel,]` to `Tuple[CLIPTokenizer, CLIPTextModel, UNet2DConditionModel,]`. Please let me whether it works.

Okay, it works, we need also import List and turn all 'list' to 'List'. By the way, how much size should my GPU has, I only have one 11G 2080t GPU, it seems the model weights beyond GPU memory when I running gradio/app.py and infer.py.

**Comment by ResearcherXman** [comment]
I will fix these typos soon.

For GPUs less 24GB VRAM, you can try some optimizations to reduce memory (torch2.x, offload_cpu, xformer, etc.). But to be honest, 11GB is kind of too small to handle SDXL models.

**Comment by Exuan148** [comment]
> I will fix these typos soon.
> 
> For GPUs less 24GB VRAM, you can try some optimizations to reduce memory (torch2.x, offload_cpu, xformer, etc.). But to be honest, 11GB is kind of too small to handle SDXL models.

Many thanks.
