### ISSUE TITLE
大卫石膏像的风格咋设置的呀

### ISSUE THREAD

**Issue by xuyu666** [InstantID/InstantID#76]
作者您好：
您的论文很棒，特别是Demo，我玩了好几个小时。其中特别感兴趣您论文上的石膏风格的转化，但是在Demo里我不知道咋设置这种效果，您可以解答下么。

**Comment by haofanwang** [comment]
Please refer to [style template](https://github.com/ahgsql/StyleSelectorXL/blob/main/sdxl_styles.json). You can generate it via prompt.

**Comment by xuyu666** [comment]
okay, thanks!
