### ISSUE TITLE
tokens limit

### ISSUE THREAD

**Issue by lavrenkov-sketch** [InstantID/InstantID#79]
Get error: `The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', intricate, elegant, highly detailed, 2 d motifs detailed dark fantasy digital painting, artstation, concept art, smooth, sharp focus, illustration, reflector light in backfront, dirty wt skin, holes on the body, art by otomo katsuhiro and shirå masamune and oshii mamoru,. vibrant, beautiful, painterly, detailed, textural, artistic']
`
if run with promt: 
`Cyberpunk,sci-fi,dark-fantasy,kodak portrait 400,8k,soft light,volumetric lighting,highly detailed,photo of a broken ruined cyborg man in a landfill + face, grey-blue eyes, body is broken with scares and holes,half the face is android,laying on the ground,missing legs,raining,night,intricate,elegant,highly detailed,2D motifs detailed dark fantasy digital painting,artstation,concept art,smooth,sharp focus,illustration,reflector light in backfront,dirty wt skin,holes on the body`

it's okay?

**Comment by haofanwang** [comment]
You can refer to [this example](https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py) to support longer prompt. In our code, we just want to make it simple and clear.

**Comment by zewolf5** [comment]
This seems to work ("pip install compel" first);

```
from compel import Compel, ReturnedEmbeddingsType

prompt = "a woman riding a horse, " + "in a dark forest, "*30 + " red hair, long hair"
negative = "red jacket"

pipe = StableDiffusionXLInstantIDPipeline........

...

compel = Compel(tokenizer=[pipe.tokenizer, pipe.tokenizer_2], text_encoder=[pipe.text_encoder, pipe.text_encoder_2], returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED, requires_pooled=[False, True], truncate_long_prompts=False)

conditioning, pooled = compel([prompt, negative])

image = pipe(
        #prompt = myoldshortprompt,
        prompt_embeds=conditioning[0:1],
        pooled_prompt_embeds=pooled[0:1],
        negative_prompt_embeds=conditioning[1:2],
        negative_pooled_prompt_embeds=pooled[1:2],
        ...
    ).images[0]
    
    
```

**Comment by ResearcherXman** [comment]
Added.
