### ISSUE TITLE
Poorly worded text in the gradio UI

### ISSUE THREAD

**Issue by andybak** [InstantID/InstantID#86]
> (Optionally) upload another person image as reference pose. If not uploaded, we will use the first person image to extract landmarks. If you use a cropped face at step1, it is recommeneded to upload it to extract a new pose.

I struggle to parse this sentence. 

1. "Another person image" - an image of another person or another image of the same person?
2. "we will use the first person image to extract landmarks" - what are landmarks? What is the effect of only uploading one image?
3. "If you use a cropped face at step1, it is recommeneded to upload it to extract a new pose" - This sounds like you're saying "Upload the same photo in both slots" but that sounds incorrect. Do you mean "Upload the original uncropped version in the second slot?
4. "recommeneded" is a typo

**Comment by haofanwang** [comment]
Thanks. We will fix these in our next update.
