### ISSUE TITLE
Sd 1.5

### ISSUE THREAD

**Issue by alexblattner** [InstantID/InstantID#93]
Hello, great job on the repo. Your paper mentioned that this does work with sdxl and 1.5. how do I use this for sd 1.5?

**Comment by haofanwang** [comment]
We won't release SD1.5 recently, but we encourage the community to re-implement.

**Comment by preposition17** [comment]
> We won't release SD1.5 recently, but we encourage the community to re-implement.

Your paper says "conducted on 48 NVIDIA H800 GPUs". is it possible to re-implement by community without use of large computing power?

**Comment by jireh-father** [comment]
Please SD1.5

**Comment by loboere** [comment]
please release sd1.5

**Comment by sir1st** [comment]
please release sd1.5

**Comment by sir1st** [comment]
i try to change the sdxl code using the sd1.5 pipeline, but failed for the uncorrected tensor size.. is it possible to use sd1.5 with the sdxl .bin and .safetensors files?
