### ISSUE TITLE
Couldn't connect to the Hub: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/wangqixun/YamerMIX_v8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f576843bbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: a80ced73-6d79-42ae-b987-b8eb8debc5b3)').

### ISSUE THREAD

**Issue by Aruen24** [InstantID/InstantID#97]
python gradio_demo/app.py

Couldn't connect to the Hub: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/wangqixun/YamerMIX_v8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f576843bbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: a80ced73-6d79-42ae-b987-b8eb8debc5b3)').
Will try to load from local cache.
Traceback (most recent call last):
  File "/home/wyw/anaconda3/envs/instantid/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/wyw/anaconda3/envs/instantid/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/wyw/anaconda3/envs/instantid/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

**Comment by haofanwang** [comment]
Refer to [download](https://github.com/InstantID/InstantID?tab=readme-ov-file#download)

**Comment by Aruen24** [comment]
> Refer to [download](https://github.com/InstantID/InstantID?tab=readme-ov-file#download)
local has dowloaded

OSError: Cannot load model wangqixun/YamerMIX_v8: model is not cached locally and an error occured while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.

**Comment by haofanwang** [comment]
I mean you can use hf-mirror to download. If it still doesn't work, please download it manually.

**Comment by jweden33** [comment]
> > 参考[下载](https://github.com/InstantID/InstantID?tab=readme-ov-file#download)本地已下载
> 
> OSError：无法加载模型 wangqixun/YamerMIX_v8：模型未缓存到本地，尝试从 Hub 获取元数据时出错。请在上面的堆栈跟踪中查看根本原因。
> 
> base_model = 'wangqixun/YamerMIX_v8' # from https://civitai.com/models/84040?modelVersionId=196039

我也遇到了同样的问题 请问您是如何解决的

**Comment by jweden33** [comment]
> 我的意思是你可以使用 hf-mirror 下载。如果仍然不起作用，请手动下载。

请问手动下载后放在哪个文件夹下？
