### ISSUE TITLE
How to use another reference image to guide the pose generation?

### ISSUE THREAD

**Issue by zengjie617789** [InstantID/InstantID#98]
As the code seen, the results only can generate the pose in the referenced face input, such as a portrait style. 
However it can uploda another image in hugging face space playground, is there anything differenct code between them?

**Comment by haofanwang** [comment]
The idea for novel view synthesis is quite simple, you just need to extract [face_kps](https://github.com/InstantID/InstantID/blob/main/infer.py#L67) from another reference image.

**Comment by zengjie617789** [comment]
thanks very much, I did this before and the results is amazing.About the great work, here are some questions below:
First, I found the results got mess when controlnet_conditioning_scale set to 0, and does it mean the IdentityNet play a key role?
Second, IdentityNet offers ID embedding and spatial informations during inference and the input is only face landmark, what about added  more Prior knowledge such as openpose map combined with face embeding?
Finaly, how about replace IdentityNet with Spatial Lora model?
